const TOTAL_BOAT_FRAMES = 7

const EXPAND_FRAMES = [0, 1]
const IN_TO_OUT_FRAME = 2
const CONTRACT_FRAMES = [3, 4, 5]
const OUT_TO_IN_FRAME = 6

export {
  TOTAL_BOAT_FRAMES,
  EXPAND_FRAMES,
  IN_TO_OUT_FRAME,
  CONTRACT_FRAMES,
  OUT_TO_IN_FRAME,
}
